### ISSUE TITLE
Master playlist detection

### ISSUE THREAD

**Issue by mauricioabreu** [rutgersc/m3u8-rs#13]
Hello!

I was reading your source code and I came across master playlist detection here: https://github.com/rutgersc/m3u8-rs/blob/master/src/lib.rs#L229

Are `#EXT-X-SESSION-KEY` and `#EXT-X-SESSION-DATA` master playlist tags?

**Comment by rutgersc** [comment]
Hey! Yes, I believe they should be master tags. At least if we're to believe [this table of contents](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-1):
```
4.3.4.  Master Playlist Tags  . . . . . . . . . . . . . . . .  24
  4.3.4.1.  EXT-X-MEDIA . . . . . . . . . . . . . . . . . . .  24
    4.3.4.1.1.  Rendition Groups  . . . . . . . . . . . . . .  27
  4.3.4.2.  EXT-X-STREAM-INF  . . . . . . . . . . . . . . . .  28
    4.3.4.2.1.  Alternative Renditions  . . . . . . . . . . .  31
  4.3.4.3.  EXT-X-I-FRAME-STREAM-INF  . . . . . . . . . . . .  32
  4.3.4.4.  EXT-X-SESSION-DATA  . . . . . . . . . . . . . . .  33
  4.3.4.5.  EXT-X-SESSION-KEY . . . . . . . . . . . . . . . .  34
```

Also note that my implementation is probably lacking on a lot of fronts, so don't look into it too much 😄

**Comment by mauricioabreu** [comment]
@rutgersc you are right! Sorry for this false alarm.

Your code is very nice tbh
