### ISSUE TITLE
Split out types

### ISSUE THREAD

**Issue by marieell** [rutgersc/m3u8-rs#14]
There are two users of this crate (the streaming servers rectangle-device and javelin) which only use the types (`MediaPlaylist`, `MediaPlaylistType`, `MediaSegment`). It would be nice to either split them out or put the parsing functionality behind a feature.

**Comment by rutgersc** [comment]
Good suggestion, those feature attributes seem like a good fit for this, so i've gone ahead and put the parser behind one.
