### ISSUE TITLE
Version 1.0.7 is not pushed to repo

### ISSUE THREAD

**Issue by marieell** [rutgersc/m3u8-rs#15]

**Comment by thaytan** [comment]
As far as I can tell, there were no actual code changes in 1.0.7, only in the Cargo.toml

**Comment by marieell** [comment]
Definitely not the actual version bump in Cargo.toml :)

**Comment by thaytan** [comment]
Yes, I think that might be all that's actually missing, based on comparing the cargo.io upload to the repo contents.

**Comment by rutgersc** [comment]
Ah my bad guys, forgot to push that one! It's indeed just the version bump  https://github.com/rutgersc/m3u8-rs/commit/64de5e4d9b7d250174a904f05a9ed7fda73d71f3
