### ISSUE TITLE
CLOSED-CAPTIONS fix needs publishing

### ISSUE THREAD

**Issue by vagetman** [rutgersc/m3u8-rs#43]
Hi,

Thank you for fixing the CLOSED-CAPTIONS issue, I just ran on it yesterday. Somehow it works only if I clone and reference the library locally and not when built from crates.io. Probably deserves 3.0.1 version and publishing?

.... as you there :) Can you please update README.md ? Thanks a bunch!! ❤️

**Comment by rutgersc** [comment]
Should be up now
