### ISSUE TITLE
Disable default-features on cargo dependency to avoid CVE issues with its time crate dependency

### ISSUE THREAD

**Issue by rcollins112** [rutgersc/m3u8-rs#56]
When running `cargo deny` to check for advisories on this crate, a failure is reported due the `chrono` crate dependency, which has a dependency on a problematic version of the `time` crate which has an outstanding CVE (https://rustsec.org/advisories/RUSTSEC-2020-0071)
`cargo deny check advisories`
This can be resolved by disabling `default-features` on the chrono crate and enabling only the `std` feature:
```
chrono = { version = "0.4", default-features = false, features = [ "std" ] }
```
Please consider making this change as I'd like to try using this crate in a project which requires checking advisories on every build.
I'm happy to fork the repo and open a PR myself if preferred.

**Comment by sdroege** [comment]
Please create a PR, yes. Thanks for noticing this, that was simply an oversight on my side when adding the chrono dependency.

However I thought the chrono problem was solved some weeks ago finally? Nonetheless would be a good idea to change this here, and if it's just to keep the dependency tree smaller.

**Comment by sdroege** [comment]
Looking at https://github.com/chronotope/chrono/blob/main/Cargo.toml there is no dependency on `time` anymore, but in https://github.com/chronotope/chrono/blob/v0.4.22/Cargo.toml it still is.

It was removed in https://github.com/chronotope/chrono/commit/4c351b1e720a30a6e32068fe386293b36d0e86fd which will be part of chrono 0.5.
