### ISSUE TITLE
for master, no comma before URI for #EXT-X-I-FRAME-STREAM-INF on write_to

### ISSUE THREAD

**Issue by vagetman** [rutgersc/m3u8-rs#6]
For simplicity I'm going to refer to one of your example manifests

https://docs.rs/crate/m3u8-rs/1.0.5/source/sample-playlists/master-with-i-frame-stream-inf.m3u8

if simply ingested and playlist.write_to() it converts

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=86000,CODECS="c1",RESOLUTION=1x1,VIDEO="1",URI="low/iframe.m3u8"

into 

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=86000,CODECS="c1",RESOLUTION=1x1,VIDEO="1"URI="low/iframe.m3u8"

I believe the code responsible to this is the follow:

        if self.is_i_frame {
            write!(w, "#EXT-X-I-FRAME-STREAM-INF:")?;
            self.write_stream_inf_common_attributes(w)?;
            writeln!(w, "URI=\"{}\"", self.uri)
        }
        else {
            write!(w, "#EXT-X-STREAM-INF:")?;
            self.write_stream_inf_common_attributes(w)?;
            write_some_attribute_quoted!(w, ",AUDIO", &self.audio)?;
            write_some_attribute_quoted!(w, ",SUBTITLES", &self.subtitles)?;
            write_some_attribute_quoted!(w, ",CLOSED-CAPTIONS", &self.closed_captions)?;
            write!(w, "\n")?;
            writeln!(w, "{}", self.uri)
        }
    }

The RFC8216 states
   Every EXT-X-I-FRAME-STREAM-INF tag MUST include a BANDWIDTH attribute
   and a URI attribute.

Since BANDWIDTH is already included in the write_stream_inf_common_attributes, so it is safe to simply add comma "," in front of the URI attribute.

**Comment by rutgersc** [comment]
Thank you for the detailed write-up. The comma should clearly be there, so i've merged your PR right away.
