### ISSUE TITLE
Make target duration a u64

### ISSUE THREAD

**Issue by Orange-Murker** [rutgersc/m3u8-rs#68]
Unlike the segment duration in EXTINF, EXT-X-TARGETDURATION can only be a decimal-integer according to the RFC.
The motivation behind this issue is that players can refuse playback if the user of the library sets this to a non-integer value and it is better to eliminate the possibility of this happening.

**Comment by vagetman** [comment]
```
   #EXT-X-TARGETDURATION:<s>

   where s is a decimal-integer indicating the Target Duration in
   seconds. 
```

Makes sense to me

**Comment by vagetman** [comment]
It's currently defined as  `f32`

https://github.com/rutgersc/m3u8-rs/blob/b9cf88b7ec4294a7a8a8b1ae75ff2673f167b14d/src/parser.rs#L344-L347

**Comment by rutgersc** [comment]
There are probably users who ingest floaty TARGETDURATIONs that will now fail to parse, but we'll see.
