### ISSUE TITLE
duplication of X-EXT-KEY and X-EXT-MAP fields for media manifest

### ISSUE THREAD

**Issue by vagetman** [rutgersc/m3u8-rs#8]
The current code allows the duplication of  #X-EXT-KEY and #X-EXT-MAP tags when a manifest is injected in and then written out to another file. For example, the following 

```
EXTM3U
#EXT-X-TARGETDURATION:5
#EXT-X-VERSION:7
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="./slow_loading.php?delay=5&resource=crypt0.key",IV=0xbf9840dc7d7fa163301a6c38844d6239
#EXT-X-MAP:URI="main.mp4",BYTERANGE="560@0"
#EXTINF:4.96907,    
#EXT-X-BYTERANGE:25312@560
main.mp4
#EXTINF:4.96907,    
#EXT-X-BYTERANGE:25440@25872
main.mp4
#EXTINF:4.96907,    
#EXT-X-BYTERANGE:25440@51312
main.mp4
#EXTINF:4.96907,    
#EXT-X-BYTERANGE:25440@76752
main.mp4
```

becomes 

```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:0,EXTM3U
#EXT-X-BYTERANGE:25312@560
#EXT-X-KEY:METHOD=AES-128,URI="./slow_loading.php?delay=5&resource=crypt0.key",IV=0xbf9840dc7d7fa163301a6c38844d6239
#EXT-X-MAP:URI="main.mp4",BYTERANGE=560@0
#EXTINF:4.96907,    
main.mp4
#EXT-X-BYTERANGE:25440@25872
#EXT-X-KEY:METHOD=AES-128,URI="./slow_loading.php?delay=5&resource=crypt0.key",IV=0xbf9840dc7d7fa163301a6c38844d6239
#EXT-X-MAP:URI="main.mp4",BYTERANGE=560@0
#EXTINF:4.96907,    
main.mp4
#EXT-X-BYTERANGE:25440@51312
#EXT-X-KEY:METHOD=AES-128,URI="./slow_loading.php?delay=5&resource=crypt0.key",IV=0xbf9840dc7d7fa163301a6c38844d6239
#EXT-X-MAP:URI="main.mp4",BYTERANGE=560@0
#EXTINF:4.96907,    
main.mp4
#EXT-X-BYTERANGE:25440@76752
#EXT-X-KEY:METHOD=AES-128,URI="./slow_loading.php?delay=5&resource=crypt0.key",IV=0xbf9840dc7d7fa163301a6c38844d6239
#EXT-X-MAP:URI="main.mp4",BYTERANGE=560@0
#EXTINF:4.96907,    
main.mp4
```

(the example is from https://stackoverflow.com/questions/12906820/any-m3u8-playlist-example-to-use-ext-x-map-tag)

**Comment by rutgersc** [comment]
Agreed, this is certainly not what should happen. However i'm not exactly sure about the fix, couldn't this also be done in the `write_to` instance of `MediaPlaylist`? I guess it depends on how people use the key/map in their code, as setting key/map to `None` now could possibly break stuff for someone else.

**Comment by vagetman** [comment]
Here is the complete block:

```
                        SegmentTag::Uri(u) => {
                            next_segment.key = encryption_key.clone();
                            next_segment.map = map.clone();
                            next_segment.uri = u;
                            media_playlist.segments.push(next_segment);
                            next_segment = MediaSegment::empty();
                            encryption_key = None;
                            map = None;
                        }
```

What the fix does is dropping the values AFTER they were used to populate `next_segment.key` and `next_segment.map`. The problem with those today is that they are not reset on the next segment tag and are inherited from a previous one. This is what a player does naturally, so this tag duplication is excessive. I believe this is the right place to fix it, as it should be ingested the same way it is in the manifest.

**Comment by rutgersc** [comment]
Yeah that's how the code should be used indeed, and it mirrors the way it's parsed. I'll cherrypick it directly, since #9 now also contains the nom stuff. Thanks again for helping :thumbsup:.
